# Generated by Django 6.0.1 on 2026-01-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/users_images', verbose_name='аватар'),
        ),
    ]
