# Generated by Django 6.0.1 on 2026-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(choices=[('base_avatar.jpg', 'Стандартный аватар'), ('avatars/avatar1.jpg', 'Аватар 1'), ('avatars/avatar2.jpg', 'Аватар 2'), ('avatars/avatar3.jpg', 'Аватар 3'), ('avatars/avatar4.jpg', 'Аватар 4'), ('avatars/avatar5.jpg', 'Аватар 5'), ('avatars/avatar6.jpg', 'Аватар 6'), ('avatars/avatar7.jpg', 'Аватар 7')], default='base_avatar.jpg', max_length=100, verbose_name='Аватар'),
        ),
    ]
