# Generated by Django 6.0.1 on 2026-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(default='Image-not-found.png', max_length=100, verbose_name='Имя файла изображения'),
        ),
    ]
