# Generated by Django 6.0.1 on 2026-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/goods_images', verbose_name='Изображение'),
        ),
    ]
